name: Sample app

on:
  workflow_dispatch:
  schedule:
    # each 5th day of month
    - cron: "0 0 5 * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Run tests
      run: ./run_sample_tests.sh
